export let products = [
  {
    id: 1,
    title: "Fad Amarilla",
    price: 100000,
    stock: 4,
    description: "Bicicleta ideal para moverte por la ciudad",
    category: "fixed-gear",
    img: "https://res.cloudinary.com/dedtdl2ee/image/upload/v1697059218/fad-fixed-amarilla_lyyies.jpg",
  },
  {
    id: 2,
    title: "Mercury Violeta",
    price: 145000,
    stock: 5,
    description: "Ultra liviana para moverte en la ciudad",
    category: "fixed-gear",
    img: "https://res.cloudinary.com/dedtdl2ee/image/upload/v1697059254/Mercury-fixed-violeta_dl9xaj.jpg",
  },
  {
    id: 3,
    title: "Orbea",
    price: 1900000,
    stock: 2,
    description: "Con doble suspension para superar todo tipo de obstaculos",
    category: "mountain-bike",
    img: "https://res.cloudinary.com/dedtdl2ee/image/upload/v1697059255/Orbea_Occam_2020_iuiwxz.jpg",
  },
  {
    id: 4,
    title: "Canyon Road",
    price: 1780000,
    stock: 2,
    description: "Bicicleta premium de carbono, Agil y veloz",
    category: "road",
    img: "https://res.cloudinary.com/dedtdl2ee/image/upload/v1697059255/canyon_ultimate_cf_slx_8_review_gtc1gg.jpg",
  },
  {
    id: 5,
    title: "Firebird mtb",
    price: 178000,
    stock: 5,
    description: "Ideal para la ciudad o terrenos mixtos",
    category: "mountain-bike",
    img: "https://res.cloudinary.com/dedtdl2ee/image/upload/v1697059275/592156-1200-auto_pzshkc.png",
  },
];
